# Generated by Django 3.0.5 on 2020-04-12 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cell',
            old_name='type',
            new_name='color',
        ),
        migrations.AddField(
            model_name='player',
            name='cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Cell'),
        ),
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(choices=[('R', 'Red'), ('B', 'Blue')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='backend.Player'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(default='G', max_length=50)),
                ('number_of_cells', models.IntegerField(default=1)),
                ('found', models.ManyToManyField(to='backend.Cell')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Team')),
            ],
        ),
    ]
