# Generated by Django 3.0.5 on 2020-04-14 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200412_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='x',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='y',
        ),
        migrations.AddField(
            model_name='game',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
