# Generated by Django 3.0.5 on 2020-04-26 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_game_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='backend.Game'),
        ),
    ]
