# Generated by Django 3.0.5 on 2020-04-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20200426_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='status',
            field=models.CharField(default='P', max_length=50),
        ),
    ]
