# Generated by Django 3.0.5 on 2020-04-28 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20200427_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='backend.Cell'),
        ),
    ]
