# Generated by Django 3.0.5 on 2020-04-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20200428_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='valid_choice',
            field=models.BooleanField(default=False),
        ),
    ]
