# Generated by Django 3.0.5 on 2020-04-29 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20200429_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='backend.Team'),
            preserve_default=False,
        ),
    ]
